version: '3.8'

services:
  updater:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tesouro-updater
    volumes:
      - ./public:/app/public
    environment:
      - TZ=UTC
    command: ["./update", "--outdir", "/app/public"]
